version: '2.1'
services:
  cms:
    image: gentics/cms:5.31.2
    restart: always
    volumes:
      - ./cms/dbfiles:/Node/node/content/dbfiles
      - ./cms/bundles:/Node/node/system/bundles
      - ./cms/conf.d:/Node/etc/conf.d
      - ./cms/packages:/Node/node/content/packages
    environment:
      NODE_USER_PASSWORD: "node"
      NODE_DB_USER: root
      NODE_DB_PASSWORD: ""
      NODE_DB_HOST: db
    depends_on:
      db:
        condition: service_started
  db:
    image: mariadb:10.3
    command: --sql-mode=""
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: ""
  elastic:
    build: ./elastic
  languagetool:
    image: gentics/languagetool
